//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xomorod.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class cdn_changer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal cdn_changer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xomorod.Resources.cdn_changer", typeof(cdn_changer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cdn.
        /// </summary>
        internal static string angular_cookies_min_js {
            get {
                return ResourceManager.GetString("angular_cookies_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cdn.
        /// </summary>
        internal static string angular_marked_js {
            get {
                return ResourceManager.GetString("angular_marked_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cdn.
        /// </summary>
        internal static string angular_min_js {
            get {
                return ResourceManager.GetString("angular_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local.
        /// </summary>
        internal static string angular_translate_loader_url_min_js {
            get {
                return ResourceManager.GetString("angular_translate_loader_url_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local.
        /// </summary>
        internal static string angular_translate_min_js {
            get {
                return ResourceManager.GetString("angular_translate_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local.
        /// </summary>
        internal static string animate_min_css {
            get {
                return ResourceManager.GetString("animate_min_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local.
        /// </summary>
        internal static string app_js {
            get {
                return ResourceManager.GetString("app_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cdn.
        /// </summary>
        internal static string bootstrap_min_css {
            get {
                return ResourceManager.GetString("bootstrap_min_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cdn.
        /// </summary>
        internal static string bootstrap_min_js {
            get {
                return ResourceManager.GetString("bootstrap_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cdn.
        /// </summary>
        internal static string bootstrap_toggle_min_css {
            get {
                return ResourceManager.GetString("bootstrap_toggle_min_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cdn.
        /// </summary>
        internal static string bootstrap_toggle_min_js {
            get {
                return ResourceManager.GetString("bootstrap_toggle_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cdn.
        /// </summary>
        internal static string font_awesome_min_css {
            get {
                return ResourceManager.GetString("font_awesome_min_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local.
        /// </summary>
        internal static string jquery_easing_min_js {
            get {
                return ResourceManager.GetString("jquery_easing_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local.
        /// </summary>
        internal static string jquery_fittext_min_js {
            get {
                return ResourceManager.GetString("jquery_fittext_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cdn.
        /// </summary>
        internal static string jquery_min_js {
            get {
                return ResourceManager.GetString("jquery_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local.
        /// </summary>
        internal static string marked_min_js {
            get {
                return ResourceManager.GetString("marked_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local.
        /// </summary>
        internal static string respond_min_js {
            get {
                return ResourceManager.GetString("respond_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local.
        /// </summary>
        internal static string wow_min_js {
            get {
                return ResourceManager.GetString("wow_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local.
        /// </summary>
        internal static string xomorod_css {
            get {
                return ResourceManager.GetString("xomorod_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local.
        /// </summary>
        internal static string xomorod_dialog_css {
            get {
                return ResourceManager.GetString("xomorod_dialog_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local.
        /// </summary>
        internal static string xomorod_js {
            get {
                return ResourceManager.GetString("xomorod_js", resourceCulture);
            }
        }
    }
}
