//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xomorod.Helper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Patterns {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Patterns() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xomorod.Helper.Patterns", typeof(Patterns).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&lt;div class=&quot;data up&quot;&gt;&lt;)[\w*\=? ?\&quot;?\.?\(?\&apos;?\:?\/?\#?\,?\)?\;?\&gt;?\&lt;?\-?]*(\/&gt;) ?(?&lt;number&gt;[\d\,]*).
        /// </summary>
        internal static string AlexaGlobalRank {
            get {
                return ResourceManager.GetString("AlexaGlobalRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http:\/\/\w*.?alexa.com\/site\/linksin\/.*(?&lt;number&gt;\d+).
        /// </summary>
        internal static string AlexaLinksin {
            get {
                return ResourceManager.GetString("AlexaLinksin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&lt;div class=&quot;data&quot;&gt;&lt;)[\w*\=? ?\&quot;?\.?\(?\&apos;?\:?\/?\#?\,?\)?\;?\&gt;?\&lt;?\-?]*(\/&gt;) ?(?&lt;number&gt;[\d\,]*).
        /// </summary>
        internal static string AlexaLocalRank {
            get {
                return ResourceManager.GetString("AlexaLocalRank", resourceCulture);
            }
        }
    }
}
